'data.root':
  type: data
  pretty-name: 'Data'
  group: Gdata

'ttbartwbb4linclusive.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttll
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l})'
  order: 9

'ttbartwbb4linclusive_Bin0.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin0
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin0}'
  order: 9

'ttbartwbb4linclusive_Bin1.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin1
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin1}'
  order: 10

'ttbartwbb4linclusive_Bin2.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin2
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin2}'
  order: 11

'ttbartwbb4linclusive_Bin3.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin3
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin3}'
  order: 12

'ttbartwbb4linclusive_Bin4.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin4
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin4}'
  order: 13

'ttbartwbb4linclusive_Bin5.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin5
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin5}'
  order: 14

'ttbartwbb4linclusive_Bin6.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin6
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin6}'
  order: 15

'ttbartwbb4linclusive_Bin7.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin7
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin7}'
  order: 16

'ttbartwbb4linclusive_Bin8.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin8
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin8}'
  order: 17

'ttbartwbb4linclusive_Bin9.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin9
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin9}'
  order: 18

'ttbartwbb4linclusive_Bin10.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin10
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin10}'
  order: 19

'ttbartwbb4linclusive_Bin11.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin11
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin11}'
  order: 20

'ttbartwbb4linclusive_Bin12.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin12
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin12}'
  order: 21

'ttbartwbb4linclusive_Bin13.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin13
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin13}'
  order: 22

'ttbartwbb4linclusive_Bin14.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin14
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin14}'
  order: 23

'ttbartwbb4linclusive_Bin15.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttllbin15
  yields-group: '1t#bar{t}+tW(\ell\ell\textrm{ bb4l}) #textrm{Bin15}'
  order: 24

#'ttbarbgFromDilepton.root':
#  type: mc
#  cross-section: 1.0
#  generated-events: 1.0
#  group: Gttbkg
#  yields-group: '2t#bar{t}\;(\textrm{not dileptonic})'
#  order: 7

'ttbarbgFromLjets.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttbkg
  yields-group: '2t#bar{t}\;(\textrm{not dileptonic})'
  order: 6

'ttbarbgFromHadronic.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gttbkg
  yields-group: '2t#bar{t}\;(\textrm{not dileptonic})'
  order: 5

'singletw.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gst
  yields-group: '3Single top'
  order: 4

'singletop.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 4

'dy.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gdy
  yields-group: '4Z+jets'
  order: 8

'ttbarX.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 3

'diboson.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 2

'wjets.root':
  type: mc
  cross-section: 1.0
  generated-events: 1.0
  group: Gother
  yields-group: '5Other'
  order: 1

