'h_chi2_S5':
  x-axis-range: [0, 950]
  y-axis-format: "%1% / %2$.0f"
  save-extensions: ['pdf', 'png']

'h_chi2_SMTop_mass_S5':
  x-axis: 'm_{t}^{hadronic} (GeV)'
  save-extensions: ['pdf', 'png']

'h_chi2_SMTop_pt_S5':
  x-axis: 't_{hadronic} p_{T} (GeV)'
  save-extensions: ['pdf', 'png']

'h_chi2_SMTop_pt_notoppt_S5':
  x-axis: 't_{hadronic} p_{T} (GeV)'
  save-extensions: ['pdf', 'png']

'h_chi2_SMW_mass_S5':
  x-axis: 'm_{W}^{hadronic} (GeV)'
  save-extensions: ['pdf', 'png']
