'DNN':
  x-axis: "DNN score"
  #x-axis: "Muon p_{T} (GeV)"
  #x-axis: "#tau_{h} p_{T} (GeV)"
  #x-axis: "Leading jet p_{T} (GeV) (GeV)"
  #x-axis: "Subleading jet p_{T} (GeV)"
  #x-axis: "Mass of #mu + #tau_{h} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / bin"
  log-y: true
  log-x: true
  sort-by-yields: true
  save-extensions: ['pdf','png']
  for-yields: true
  yields-table-order: 0
  yields-title: 'DNN'
  ratio-y-axis-range: [0.7, 1.3]
  #ratio-y-axis-range: [0.5, 2.0]
  ratio-y-axis-auto-range: true

  #signal-normalize-data: false
  #labels:
  #  - {text: 'ct', position: [0.2, 0.806], size: 18, font: 44}
